### ISSUE TITLE
Feature request: Chat Mode?

### ISSUE THREAD

**Issue by scythe000** [ickybodclay/adventurebot#1]
This project looks awesome!
Have you thought of also having a chatbot mode?

**Comment by ickybodclay** [comment]
@scythe000 Chat Mode works!  You'd just need to toggle it in KoboldAI WebUI settings.  

To clear things up, this is not a standalone project.  It is actually just a bot wrapper around KoboldAI using their new Web API.

Here is a good demo of it in action (a little long, but you'll get the idea after a turn or two):
https://www.youtube.com/watch?v=Vmj6-tFSsuo
